apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 910911502135.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend-kyoungschoi
  newName: 910911502135.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend-kyoungschoi
  newTag: e7d7103b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
